export default interface Ecole {
  identifiant_de_l_etablissement
  nom_etablissement
  type_etablissement
  statut_public_prive
  adresse_1
  adresse_2
  adresse_3
  code_postal
  code_commune
  nom_commune
  code_departement
  code_academie
  code_region
  ecole_maternelle
  ecole_elementaire
  voie_generale
  voie_technologique
  voie_professionnelle
  telephone
  fax
  web
  mail
  restauration
  hebergement
  ulis
  apprentissage
  segpa
  section_arts
  section_cinema
  section_theatre
  section_sport
  section_internationale
  section_europeenne
  lycee_agricole
  lycee_militaire
  lycee_des_metiers
  post_bac
  appartenance_education_prioritaire
  greta
  siren_siret
  nombre_d_eleves
  fiche_onisep
  position: {
    lat,
    lng
  }
  type_contrat_prive
  libelle_departement
  libelle_academie
  libelle_region
  coordx_origine
  coordy_origine
  epsg_origine
  nom_circonscription
  latitude
  longitude
  precision_localisation
  date_ouverture
  date_maj_ligne
  etat
  ministere_tutelle
  multi_uai
  rpi_concentre
  rpi_disperse
  code_nature
  libelle_nature
  code_type_contrat_prive
  pial
  etablissement_mere
  type_rattachement_etablissement_mere
  code_zone_animation_pedagogique
  libelle_zone_animation_pedagogique
}
